#!/usr/bin/env ruby

require 'pp'
require 'ofx_reader'

if ARGV[0]
  if File.exist?(ARGV[0])
    ofx_text = File.read(ARGV[0])
    ofx = OFXReader::Parser::OFX102.new(ofx_text)
    pp ofx.headers
    pp ofx.account
    pp ofx.transactions
  else
    puts "File doen't exist"
  end
else
  puts "No file provided"
end
